

find_path(LEVELDB_INCLUDE_DIRS NAMES leveldb/db.h)
find_library(LEVELDB_SHARED_LIBRARIES NAMES leveldb)

if(LEVELDB_INCLUDE_DIRS AND LEVELDB_SHARED_LIBRARIES)
    set(LEVELDB_FOUND TRUE)
endif(LEVELDB_INCLUDE_DIRS AND LEVELDB_SHARED_LIBRARIES)

if(LEVELDB_FOUND)
    if(NOT LEVELDB_FIND_QUIETLY)
        message(STATUS "Found LevelDB: ${LEVELDB_SHARED_LIBRARIES}")
    endif(NOT LEVELDB_FIND_QUIETLY)
else(LEVELDB_FOUND)
    if(LevelDB_FIND_REQUIRED)
        message(FATAL_ERROR "Could not find leveldb library.")
    endif(LevelDB_FIND_REQUIRED)
endif(LEVELDB_FOUND)