name: flare-dev
channels:
  - conda-forge
  - defaults
  - flare-rpc
dependencies:
  - clang # [osx]
  - clangxx #   [osx]
  - make
  - openssl =1.1.1
  - gflags >=2.2.2
  - leveldb >=1.22
  - protobuf >=3.9.2
  - gperftools =2.9.1
  - gtest =1.11.0
  - gmock =1.11.0
  - benchmark