name: flare-dev
channels:
  - conda-forge
  - defaults
  - flare-rpc
dependencies:
  - clang # [osx]
  - clangxx #   [osx]
  - cmake =3.19.1
  - make
  - gflags =2.2.2
  - leveldb =1.22
  - protobuf =3.12.4 # includes Protobuf compiler, C++ headers, Python libraries
  - openssl =1.1.1
  - zlib
  - gperftools=2.9.1
  - gtest =1.11.0
  - gmock =1.11.0
  - benchmark