name: flare-dev
channels:
  - conda-forge
  - defaults
  - flare-rpc
dependencies:
  - cmake =3.19
  - make
  - gflags =2.2.2
  - leveldb =1.22
  - protobuf=3.12.4 # includes Protobuf compiler, C++ headers, Python libraries