package:
  name: flare
  version: "0.1.4"

source:
  git_url: ../

build:
  number: 0
  include_recipe: False

requirements:
  build:
    - make
    - cmake
  host:
    - openssl =1.1.1
    - gflags =2.2.2
    - leveldb =1.22
    - protobuf =3.12.4

about:
  home: https://github.com/flare-rpc/flare-cpp
  license: Apache License 2
  license_family: Apache License
  license_file: LICENSE
  summary: A library for c++ based libraries and rpc libraries