
{% set version = environ.get('GIT_DESCRIBE_TAG').lstrip('v') %}
{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: flare-pkg
  version: {{ version }}

build:
  number: {{ number }}

about:
  home: https://github.com/flare-rpc/flare-cpp
  license: Apache License 2
  license_family: APACHE
  license_file: LICENSE
  summary: A library for c++ based libraries and rpc libraries

source:
  git_url: ../../

outputs:
  - name: libflare
    script: build-lib.sh   # [not win]
    script: build-lib.bat  # [win]
    build:
      string: "h{{ PKG_HASH }}_{{ number }}_cpu"
      run_exports:
        - {{ pin_compatible('libflare', exact=True) }}
      ignore_run_exports:
        - mkl  # [osx]
    requirements:
      build:
        - clang # [osx]
        - clangxx #   [osx]
        - gcc =8.5 # [linux]
        - gxx =8.5 # [linux]
        - sysroot_linux-64=2.17 # [linux]
        - make
        - cmake
      host:
        - zlib
        - sysroot_linux-64=2.17 # [linux]
        - openssl =1.1.1
        - gflags =2.2.2
        - leveldb =1.22
        - protobuf =3.12.4
        - gperftools =2.9.1
      run:
        - zlib
        - sysroot_linux-64=2.17 # [linux]
        - openssl =1.1.1
        - gflags =2.2.2
        - leveldb =1.22
        - protobuf =3.12.4
        - gperftools =2.9.1
    test:
      commands:
        - test -f $PREFIX/lib/libflare.so              # [linux]
        - test -f $PREFIX/lib/libflare.dylib           # [osx]
        - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
        - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]
